/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface;

import utilities.Command;
import server.ServerWorker;
import server.Server;

/**
 *
 * @author Demo
 */
public class MainUI extends javax.swing.JFrame
{
    private final ServerWorker server;

    /**
     * Creates new form MainUI
     */
    public MainUI()
    {
        super("Server");
        setResizable(false);
        initComponents();
        server = Server.getInstance();
    }
    
    public void log(String msg) {
        logScreen.append(msg);
        logScreen.setCaretPosition(logScreen.getDocument().getLength());
    }
    
    public void errorLog(String msg) {
        errorLogScreen.append(msg);
        errorLogScreen.setCaretPosition(errorLogScreen.getDocument().getLength());
    }
    
    public void clearLog() {
        logScreen.setText("");
    }
    
    public void clearErrLog() {
        errorLogScreen.setText("");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        inputField = new javax.swing.JTextField();
        enterButton = new javax.swing.JButton();
        displayView = new javax.swing.JTabbedPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        logScreen = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        errorLogScreen = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        inputField.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyPressed(java.awt.event.KeyEvent evt)
            {
                inputFieldKeyPressed(evt);
            }
        });

        enterButton.setText("Enter");
        enterButton.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                enterButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(inputField, javax.swing.GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(enterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(inputField)
                    .addComponent(enterButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        logScreen.setEditable(false);
        logScreen.setColumns(20);
        logScreen.setRows(5);
        jScrollPane1.setViewportView(logScreen);

        displayView.addTab("Main Log", jScrollPane1);

        errorLogScreen.setColumns(20);
        errorLogScreen.setForeground(new java.awt.Color(255, 0, 0));
        errorLogScreen.setRows(5);
        errorLogScreen.setFocusable(false);
        jScrollPane2.setViewportView(errorLogScreen);

        displayView.addTab("Error Log", jScrollPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(displayView, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(displayView, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enterButtonActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_enterButtonActionPerformed
    {//GEN-HEADEREND:event_enterButtonActionPerformed
        handleCommandGiven();
    }//GEN-LAST:event_enterButtonActionPerformed

    private void inputFieldKeyPressed(java.awt.event.KeyEvent evt)//GEN-FIRST:event_inputFieldKeyPressed
    {//GEN-HEADEREND:event_inputFieldKeyPressed
        if (evt.getKeyChar() == '\n') handleCommandGiven();
    }//GEN-LAST:event_inputFieldKeyPressed

    private void handleCommandGiven() {
        String cmd = inputField.getText();
        inputField.setText("");
        
        Command command = Command.createAnonymous(cmd);
        server.processCommand(command);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane displayView;
    private javax.swing.JButton enterButton;
    private javax.swing.JTextArea errorLogScreen;
    private javax.swing.JTextField inputField;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea logScreen;
    // End of variables declaration//GEN-END:variables

    


}
